# Zettel 02 {.unnumbered}

## Aufgabe 3

Eine sprache fuer lineare Gleichungssysteme kann z.B. durch folgende EBNF-syntaxbeschreibung definiert werden:

\begin{align*}
    \langle Gleichungssystem\rangle &::= \langle Gleichung\rangle\{\underline{\backslash n} \langle Gleichung\rangle\} \\
    \langle Gleichung\rangle &::= [\langle Zahl\rangle]\underline{x}\langle Index\rangle\{\langle Vorzeichen\rangle[\langle Zahl\rangle]\underline{x}\langle Index\rangle\}\underline{=}\langle Zahl\rangle \\
    \langle Zahl\rangle  &::= \langle Ersteziffer\rangle \{\langle Ziffer\rangle \} \\
    \langle Ersteziffer\rangle  &::= \underline{1} | 
                       \underline{2} | 
                       \underline{3} |
                       \underline{4} |
                       \underline{5} |
                       \underline{6} |
                       \underline{7} |
                       \underline{8} |
                       \underline{9} | \\
    \langle Ziffer\rangle  &::= \underline{0} | \langle Ersteziffer\rangle  \\
    \langle Index\rangle  &::= \underline{_0} | \langle Subzahl\rangle  \\
    \langle Subzahl\rangle  &::= \langle Erstesubziffer\rangle \{\langle Subziffer\rangle \} \\
    \langle Erstesubziffer\rangle  &::= \underline{_1} | 
                       \underline{_2} | 
                       \underline{_3} |
                       \underline{_4} |
                       \underline{_5} |
                       \underline{_6} |
                       \underline{_7} |
                       \underline{_8} |
                       \underline{_9} | \\
    \langle Subziffer\rangle  &::= \underline{_0} | \langle Erstesubziffer\rangle  
\end{align*}

Die Anforderung "Die Anzahl der Variablen ist gleich der Anzahl der Gleichungen" ist eine Beschreibung die von dem
Kontext des Erzeugten Wortes abhaengt - gueltige Gleichungssysteme duerfen beliebige Anzahl an Variablen haben. Da 
mit EBNF nur kontextfreie Sprachen definiert werden koennen ist diese Anforderung nicht umsetzbar. 

