project:
  type: book

book:
  title: "IPI WS23/24 Solutions"
  author: "Igor Dimitrov"
  date: "10/30/2023"
  chapters:
    - index.qmd
    - 01/01.qmd
    - 02/02.qmd
    - 03/03.qmd
    - 04/04.qmd
  downloads: pdf

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    include-in-header:
      - text: |
          \usepackage{cases} 
          \usepackage{fvextra} 
          \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}



